name: Package install failed
description: _
labels: ["Type - Bug", "Needs - Review"]
body:
  - type: dropdown
    id: packageName
    attributes:
      label: Package name
      options:
        - Files stable
        - Files preview
    validations:
      required: true

  - type: textarea
    attributes:
      label: Command line output
    validations:
      required: true
